#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     colorSensor,    sensorI2CHiTechnicColor)
#pragma config(Motor,  mtr_S1_C1_1,     motorHang,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoScoop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if ( joy1Btn(2) == 1 )
			servo[servoScoop] = 255;
		else if (joy1Btn(4) == 1)
			servo[servoScoop] = 0;
		else
			servo[servoScoop] = 127;
	}

	//while ( 1)
	//{
	//	getJoystickSettings(joystick);
	//	int joyValue = joystick.joy2_y1;

	//	if ( joyValue < MAX_DEAD_ZONE && joyValue > MIN_DEAD_ZONE)
	//	{
	//			servo[servoScoop] = ServoValue[servoScoop];
	//	}
	//	else
	//	{
	//		int direction = joyValue/abs(joyValue);
	//		float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
	//		int Scaled = ratio * MAX_SERVOVAL * direction;

	//		if( LastValue < Scaled )
	//		{
	//			servo[servoScoop] = ServoValue[servoScoop]  - 2;
	//		}
	//		else
	//		{
	//			servo[servoScoop] = ServoValue[servoScoop]  + 2;
	//		}
	//	}
}
