#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    arm1,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    arm2,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//________________________________________________________________________________//

#include "JoystickDriver.c";
int scaleForMotor(int joyValue)
{

	const int MAX_MOTOR_VAL = 100;
	const float MAX_JOY_VAL = 127.0;
	const int DEADZONE = 15;


	if(abs(joyValue) < DEADZONE) {
		return 0;
	}


	int direction = joyValue / abs(joyValue);
	float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
	int scaledVal = (ratio * MAX_MOTOR_VAL) * direction;

	return scaledVal;

}


//________________________________________________________________________________//

task main()
{

	while(true)
	{

		getJoystickSettings(joystick);

		motor[leftMotor] = scaleForMotor(joystick.joy1_y1);
		motor[rightMotor] = scaleForMotor(joystick.joy1_y2);



	}

}
