#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     colorSensor,    sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorHang,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servoScoop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servoFlag,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
// scale for the drive motors
// the joy stick value should be scaled from 0 to maximum motor value
/////////////////////////////////////////////////////////////////////////////////////////////////////
int ScaleForMotor(int joyValue)
{
	const int MIN_DEAD_ZONE = -7;
	const int MAX_DEAD_ZONE = 7;
	const int MAX_MOTOR_VAL = 70;
	const float MAX_JOY_VAL = 127;

	if ( joyValue < MAX_DEAD_ZONE && joyValue > MIN_DEAD_ZONE)
		return 0;

	int direction = joyValue/abs(joyValue);
	float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
	int Scaled = ratio * MAX_MOTOR_VAL * direction;
	return Scaled;
}



void ArmDown()
{
		motor[motorArm] = -40;
		wait10Msec(10);
}

void ArmUp()
{
		motor[motorArm] = 80;
		wait10Msec(10);
}

void RackUp()
{
	motor[motorHang] = 50;
	wait10Msec(10);
}

void RackDown()
{
	motor[motorHang] = -50;
	wait10Msec(10);
}

void ServoStart()
{
	servo[servoScoop]  = 0;
}

void ServoFlat()
{
	servo[servoScoop] = 100;
}

task Arm()
{
	while(true)
	{
		getJoystickSettings(joystick);
		motor[motorArm] = ScaleForMotor(joystick.joy1_y2);
	}
}


task main()
{
	servo[servoScoop]  = 0;

  //multi tasking thread for arm
	StartTask(Arm);

	while(true)
	{
   	getJoystickSettings(joystick);

		if(joy1Btn(4) == 1)
			ArmUp();
		else if(joy1Btn(2) == 1)
			ArmDown();
		if (joystick.joy1_TopHat == 0)
			RackUp();
		else if (joystick.joy1_TopHat == 4)
			RackDown();
		if(joy1Btn(1) == 1)
			servo[servoScoop] = ServoValue[servoScoop]  + 2;
		else
			if(joy1Btn(3) == 1)
			servo[servoScoop] = ServoValue[servoScoop]  - 1;
		else
			if ( joy1Btn(5) == 1)
				servo[servoScoop] = 138;
		else if ( joy1Btn(6) == 1 )
			servo[servoScoop] = 255;
		else if ( joy1Btn(7) == 1 )
			servo[servoScoop] = 0;
		else
		{
			motor[motorHang] = 0;
		}

		//this is a test to see if the github works
		//yes this works
	}
}
