#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     colorSensor,    sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorHang,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servoScoop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servoIRDrop,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servoOuterScoop,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    servoArm,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
// scale for the drive motors
// the joy stick value should be scaled from 0 to maximum motor value
/////////////////////////////////////////////////////////////////////////////////////////////////////
int ScaleForMotor(int joyValue)
{
	const int MIN_DEAD_ZONE = -7;
	const int MAX_DEAD_ZONE = 7;
	const int MAX_MOTOR_VAL = 70;
	const float MAX_JOY_VAL = 127;

	if ( joyValue < MAX_DEAD_ZONE && joyValue > MIN_DEAD_ZONE)
		return 0;

	int direction = joyValue/abs(joyValue);
	float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
	int Scaled = ratio * MAX_MOTOR_VAL * direction;
	return Scaled;
}

void ServoArm(int value)
{
	servo[servoArm] = value;
	wait1Msec(10);
}




void ArmDown()
{
		motor[motorArm] = -30;
		wait10Msec(10);
}

void ArmUp()
{
		motor[motorArm] = 30;
		wait10Msec(10);
}

void RackUp()
{
	motor[motorHang] = 65;
	wait1Msec(50);
}

void RackDown()
{
	motor[motorHang] = -65;
	wait1Msec(50);
}

void ServoStart()
{
	servo[servoScoop]  = 0;
}

void ServoFlat()
{
	servo[servoScoop] = 100;
}

task Arm()
{
	while(true)
	{
		getJoystickSettings(joystick);
		motor[motorArm] = ScaleForMotor(joystick.joy1_y2);
	}
}

void PointTurnRight(int Seconds)
{
		motor[motorRight] = -65;
		motor[motorLeft] = 60;
		wait1Msec(Seconds);
		motor[motorRight] = 0;
		motor[motorLeft] = 0;
}

task main()
{
	servo[servoScoop]  = 130;


	servo[servoIRDrop]  = 28;

	servo[servoOuterScoop]  = 0;
			wait1Msec(30);
			servo[servoOuterScoop]  = 127;

	RackDown();
	ArmDown();


	}
