#pragma config(Sensor, S1,     HTIRS2,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"

string sTextLines[8];
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void displayText(int nLineNumber, string cChar, int nValueDC, int nValueAC);

task main()
{

int _dirDC = 0;
int _dirAC = 0;

int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;

tHTIRS2DSPMode _mode = DSP_1200;

if(HTIRS2setDSPMode(HTIRS2, _mode) == 0)
{
	eraseDisplay();
	nxtDisplayCenteredTextLine(0, "ERROR!");
	nxtDisplayCenteredTextLine(2, "Init failed!");
	nxtDisplayCenteredTextLine(3, "Connect sensor");
	nxtDisplayCenteredTextLine(4, "to Port 1.");

	PlaySound(soundBeepBeep);
	wait10Msec(300);
	return;
}

for(int i = 0; i < 8; ++i)
	sTextLines[i] = "";

	eraseDisplay();
	nxtDisplayTextLine(0, "     DC     AC");
	nxtDisplayTextLine(1, "--------------");

while(true)
{
	_dirDC = HTIRS2readDCDir(HTIRS2);
	if(_dirAC < 0)
		break;
	if(!HTIRS2readAllDCStrength(HTIRS2, dcS1, dcS2, dcS3, dcS4, dcS5))
		break;
	if(!HTIRS2readAllDCStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5))
		break;

	string d = "D";
	string zero = "0";
	string one = "1";
	string two = "2";
	string three = "3";
	string four = "4";

	displayText(2, d, _dirDC, _dirAC);
	displayText(3, zero, dcS1, acS1);
	displayText(4, one, dcS2, acS2);
	displayText(5, two, dcS3, acS3);
	displayText(6, three, dcS4, acS4);
	displayText(7, four, dcS5, acS5);

	wait10Msec(5);
}
}

void displayText(int nLineNumber, string cChar, int nValueDC, int nValueAC)
{
	string sTemp;

	StringFormat(sTemp, "%d %d", nValueDC, nValueAC);

	if (sTemp != sTextLines[nLineNumber])
 	{
 		string sTemp2;
 		sTextLines[nLineNumber] = sTemp;
 		StringFormat(sTemp2, "%s: %s", cChar, sTemp);
 		nxtDisplayTextLine(nLineNumber, sTemp2);
 }
}
