#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     colorSensor,    sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorHang,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoScoop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servoIRDrop,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servoOuterScoop,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


//number of ticks the rack has to move so that
//hook is over the bar during pull up
const int MAX_ENCODER_HANG = 26100;

//global variable to keep track of rack movement up and down,
//so that we stop at the exactly above the bar
int currentRackTicks= 0;


void initializeRobot()
{
	//initialize the scoop to vertical position
	servo[servoScoop] = 130;
	servo[servoIRDrop] = 25;
  return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
// Task: Rack
// Allows for Rack to move up and down, runs parallely along with the drive and other tasks
// Raise the Rack based on the predefined encoder value.
// TopHat 0:
// 		Moves Rack Up;
// TopHat 4:
// 		Moves Rack Down
// Left and Right bumper
// 		Stops the Rack from climbing up or down.
// TopHat 6 (alternate way to make rack go up regardless of encoder logic)
//    Rack goes up and no encoder logic, releasing stops
// TopHat 2 (alternate way to make rack go down regardless of encoder logic)
//    Rack goes down and no encoder logic, releasing stops
/////////////////////////////////////////////////////////////////////////////////////////////////////
task RackNotUsedAsEncoderWasRemoved()
{
	while(true)
	{
		int RackTicks;
		getJoystickSettings(joystick);
		if (joystick.joy2_TopHat == 0 ) //Rack Up
		{
			//initialize the encoder
			nMotorEncoder[motorHang] = 0;

			//set the target value based on the maximum value and the ticks the rack has gone up
			nMotorEncoderTarget[motorHang] = MAX_ENCODER_HANG - currentRackTicks;

			//power the motor
			motor[motorHang] = 70;

			//wait for the encoder target to be reached, or the stop button is pressed
			while( (nMotorRunState[motorHang] != runStateIdle) && (joy2Btn(6) != 1)  && (joy2Btn(5) != 1) ) //Right/left bumper is an emergency stop
			{
				//if encoder target is not met, or the emergency stop button is not pressed, continue
				getJoystickSettings(joystick);

				//read the number ticks the rack went up
				RackTicks = nMotorEncoder[motorHang];
			}

			//encoder target is reached or the emergency stop is pressed, reset the motor power to stop
			motor[motorHang] = 0;

			//keep track of the total ticks up so that the target is set correct on the next button press
			currentRackTicks = currentRackTicks + RackTicks;

		} // if

		else if(joystick.joy2_TopHat == 4 ) //Rack Down
	  {
	  	//initialize the encoder
	  	nMotorEncoder[motorHang] = 0;

	  	//set the target to go down, but only half way, we dont want to raise the robot all the way up.
			nMotorEncoderTarget[motorHang] = -(MAX_ENCODER_HANG/2);

		  //power the motor
			motor[motorHang] = -70;

			//Right and Left bumper is an emergency stop
			//wait for the encoder target to be reached, or the stop button is pressed
			while((nMotorRunState[motorHang] != runStateIdle) && (joy2Btn(6) != 1)  && (joy2Btn(5) != 1) )
			{
				//if encoder target is not met, or the emergency stop button is not pressed, continue
				getJoystickSettings(joystick);

				//read the number ticks the rack went down
				RackTicks = nMotorEncoder[motorHang];
			}
			//encoder target is reached or the emergency stop is pressed, reset the motor power to stop
			motor[motorHang] = 0;

			//keep track of the total ticks up so that the target is set correct on the next button press
			currentRackTicks = currentRackTicks + RackTicks;

	  } // else
	  else
	  	motor[motorHang] = 0;

	 // debugging purposes
	 // string sTemp;
	 // sprintf(sTemp, "%d", currentRackTicks);
	 // nxtDisplayString(2, sTemp);

	} //while true

} //Rack Task

task Rack()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if (joystick.joy2_TopHat == 0 ) //Rack Up
		{
			//power the motor
			motor[motorHang] = 65;
			wait1Msec(30);
		} // if
		else if(joystick.joy2_TopHat == 4 ) //Rack Down
	  {
			motor[motorHang] = -65;
			wait1Msec(30);
	  } // else
	  else
	  	motor[motorHang] = 0;

	} //while true

} //Rack Task
/////////////////////////////////////////////////////////////////////////////////////////////////////
// scale for the drive motors
// the joy stick value should be scaled from 0 to maximum motor value
/////////////////////////////////////////////////////////////////////////////////////////////////////
int ScaleForMotor(int joyValue)
{
	const int MIN_DEAD_ZONE = -7;
	const int MAX_DEAD_ZONE = 7;
	const int MAX_MOTOR_VAL = 70;
	const float MAX_JOY_VAL = 127;

	if ( joyValue < MAX_DEAD_ZONE && joyValue > MIN_DEAD_ZONE)
		return 0;

	int direction = joyValue/abs(joyValue);
	float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
	int Scaled = ratio * MAX_MOTOR_VAL * direction;
	return Scaled;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
// scale for the drive motors
// the joy stick value should be scaled from 0 to maximum motor value
/////////////////////////////////////////////////////////////////////////////////////////////////////
int ScaleForMotorArm(int joyValue)
{
	const int MIN_DEAD_ZONE = -7;
	const int MAX_DEAD_ZONE = 7;
	const int MAX_MOTOR_VAL = 40; //this controls the rack and keep the power at 40;
	const float MAX_JOY_VAL = 127;

	if ( joyValue < MAX_DEAD_ZONE && joyValue > MIN_DEAD_ZONE)
		return 0;

	int direction = joyValue/abs(joyValue);
	float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
	int Scaled = ratio * MAX_MOTOR_VAL * direction;
	return Scaled;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
// Task: Arm
// Allows for Arm to move up and down
// Joystick 2 - controls the movement up and down
/////////////////////////////////////////////////////////////////////////////////////////////////////
task Arm()
{
	while(true)
	{
		getJoystickSettings(joystick);
		motor[motorArm] = ScaleForMotorArm(joystick.joy2_y2);

	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
// Task: OuterRackScoop
// Allows for Arm to move further up
// Joystick 2 - controls the movement up and down
/////////////////////////////////////////////////////////////////////////////////////////////////////
task OuterRackScoop()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy2Btn(4) == 1)
		{
			//set the position zero to move reverse
			servo[servoOuterScoop]  = 0;
			wait1Msec(30);
		}
		else if(joy2Btn(2) == 1)
		{
			//set the position zero to move forward
			servo[servoOuterScoop]  = 255;
			wait1Msec(30);
		}
		else
		{
			//stop the continuous servo
			servo[servoOuterScoop]  = 127;
		}
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
// Task: Scoop
// Allows for the scoop to be controlled parallely,
// servo should be scaled from 0 to 255
// the value should be increased and decreased based on the joy stick value
/////////////////////////////////////////////////////////////////////////////////////////////////////
task Scoop()
{
	const int MIN_DEAD_ZONE = -7;
	const int MAX_DEAD_ZONE = 7;
	const int MAX_SERVOVAL  = 85;
	const float MAX_JOY_VAL = 127;
	int LastValue = 0;
	while (1)
	{
		getJoystickSettings(joystick);
		int joyValue = joystick.joy2_y1;

		//Scoop PickUp: positions the scoop in the pickup position, right in the middle
		if(joy2Btn(3) == 1)
		{
			servo[servoScoop] = 0;
			wait1Msec(20);
		}
		else if(joy2Btn(1) == 1)
		{
			servo[servoScoop] = 90;
			wait1Msec(20);
		}
		//allow scoop to be controlled with the joy stick at a faster rate
		else
		{
			if ( joyValue < MAX_DEAD_ZONE && joyValue > MIN_DEAD_ZONE)
			{
					servo[servoScoop] = ServoValue[servoScoop];
			}
			else
			{
					int direction = joyValue/abs(joyValue);
					float ratio = ((joyValue * joyValue) / (MAX_JOY_VAL * MAX_JOY_VAL));
					int Scaled = ratio * MAX_SERVOVAL * direction;

					if( LastValue < Scaled &&  Scaled <= MAX_SERVOVAL  )
					{
						servo[servoScoop] = ServoValue[servoScoop]  + 2;
					}
					else
					{
						servo[servoScoop] = ServoValue[servoScoop]  - 2;
					}
			}//else joyvalue

		}// else joy2btn

	} // while true

} // task end

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

	initializeRobot();

	motor[motorRight] = 0;
	motor[motorLeft] = 0;
	motor[motorFlag] = 0;
	motor[motorHang] = 0;
	motor[motorArm] = 0;

	//multi tasking thread for arm
	StartTask(Arm);

	//second thread for the scoop to go higher
	StartTask(OuterRackScoop);

	//multi tasking thread for scoop
	StartTask(Scoop);

	//multi threaded task to control the rack and pinion
	StartTask(Rack);


	//main thread for drive and flag
	while (true)
	{
		//coast the motors
		bFloatDuringInactiveMotorPWM = true;

		getJoystickSettings(joystick);

		//drive controls
		if ( joystick.joy1_TopHat == 0 ) //forward
		{
				motor[motorRight] = 65;
				motor[motorLeft] = 65;
		}
		else if ( joystick.joy1_TopHat  == 4 )//backward
		{
				motor[motorRight] = -50;
				motor[motorLeft] = -50;
		}
		else if ( joystick.joy1_TopHat  == 2 )//point turn left
		{
				motor[motorLeft] = 45;
				motor[motorRight] = -45;
		}
		else if ( joystick.joy1_TopHat == 1 ) //swing right
		{
				motor[motorRight] = 20;
				motor[motorLeft] = 45;
		}
		else if ( joystick.joy1_TopHat  == 6 ) //point turn right
		{
				motor[motorRight] = 45;
				motor[motorLeft] = -45;
		}
		else if ( joystick.joy1_TopHat == 7 ) //swing left
		{
				motor[motorRight] = 45;
				motor[motorLeft] = 20;
		}
		else if (joy1Btn(2) == 1)  //move backward slowly
		{
					motor[motorRight] = -20;
					motor[motorLeft] = -20;
		}
		else if (joy1Btn(7) == 1) //ramp up, goes slowly
		{
					bFloatDuringInactiveMotorPWM = false;
					motor[motorRight] = 25;
					motor[motorLeft] = 25;
		}
		else if (joy1Btn(8) == 1) //ramp down, goes slowly
		{
					bFloatDuringInactiveMotorPWM = false;
					motor[motorRight] = -30;
					motor[motorLeft] = -30;
		}
		else
		{
			motor[motorLeft] = ScaleForMotor( joystick.joy1_y1 );
			motor[motorRight] = ScaleForMotor( joystick.joy1_y2 );
		}

		//flag control
		if  (joy2Btn(8) == 1) //right trigger spin fast
		{
				motor[motorFlag] = 90;
		}
		else if  (joy2Btn(7) == 1) //left trigger go slow
		{
				motor[motorFlag] = 35;
		}
		else
		{
				motor[motorFlag] = 0;
		}

	} //while true

} // main
